version: '3.8'

services:
  # Weather API Gateway service
  weather-api-gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: weather-api-gateway-service-dev
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=9000
      # Override specific values for Docker environment
      - SERVICE_HOST=0.0.0.0
      - CACHE_STRATEGY=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - weather-network
    restart: unless-stopped

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: weather-redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-development}
    volumes:
      - redis_data:/data
    networks:
      - weather-network
    restart: unless-stopped

  # Redis Commander (Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: weather-redis-commander
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-development}
    depends_on:
      - redis
    networks:
      - weather-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  weather-network:
    driver: bridge
